name: IrukaKun
options:
  bundleIdPrefix: com.iruka-kun
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"
settings:
  base:
    SWIFT_VERSION: "6"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    GENERATE_INFOPLIST_FILE: false
    CODE_SIGN_IDENTITY: "-"
    PRODUCT_NAME: "iruka-kun"
targets:
  IrukaKun:
    type: application
    platform: macOS
    sources:
      - path: IrukaKun
        excludes:
          - "**/*.entitlements"
    resources:
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: IrukaKun/Info.plist
        CODE_SIGN_ENTITLEMENTS: IrukaKun/iruka-kun.entitlements
        PRODUCT_MODULE_NAME: IrukaKun
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
  IrukaKunTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: IrukaKunTests
    dependencies:
      - target: IrukaKun
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_NAME: "IrukaKunTests"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/iruka-kun.app/Contents/MacOS/iruka-kun"
